services:
  redis:
    container_name: sea-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - sea
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: sea-searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - sea
    ports:
      - "8081:8080"
    volumes:
      - ./searxng-docker/searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  valkey-data2:
  searxng-data:

networks:
  sea:
    driver: bridge
