models:
  "qwen3:0.6b":
    cmd: llama-server --jinja -hf Qwen/Qwen3-0.6B-GGUF --port ${PORT}
  "unsloth:qwen3:4b":
    cmd: llama-server --jinja -hf unsloth/Qwen3-4B-Instruct-2507-GGUF --port ${PORT}
  "llama3.2:1b:instruct":
    cmd: llama-server --jinja -hf unsloth/Llama-3.2-1B-Instruct-GGUF --port ${PORT}
