models:
  "qwen3:0.6b":
    cmd: llama-server --jinja -hf Qwen/Qwen3-0.6B-GGUF --port ${PORT}
  "unsloth:qwen3:4b":
    cmd: llama-server --jinja -hf unsloth/Qwen3-4B-Instruct-2507-GGUF --port ${PORT}
  "unsloth:qwen3:1.7b":
    cmd: llama-server --jinja -hf unsloth/Qwen3-1.7B-GGUF --port ${PORT}
  "llama3.2:1b:instruct":
    cmd: llama-server --jinja -hf unsloth/Llama-3.2-1B-Instruct-GGUF --port ${PORT}
  "davidau:qwen3-zero-coder-reasoning:0.8b":
    cmd: llama-server --jinja -hf DavidAU/Qwen3-Zero-Coder-Reasoning-0.8B-NEO-EX-GGUF --port ${PORT}
  "jan:v1:4b":
    cmd: llama-server --jinja -hf janhq/Jan-v1-4B-GGUF --port ${PORT}
